USE [master]
GO

/****** Object:  Database [Knjizara]    Script Date: 3.9.2022. 00:49:29 ******/
DROP DATABASE [Knjizara]
GO

/****** Object:  Database [Knjizara]    Script Date: 3.9.2022. 00:49:29 ******/
CREATE DATABASE [Knjizara]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Knjizara', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Knjizara.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Knjizara_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Knjizara_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Knjizara].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Knjizara] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Knjizara] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Knjizara] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Knjizara] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Knjizara] SET ARITHABORT OFF 
GO

ALTER DATABASE [Knjizara] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Knjizara] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Knjizara] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Knjizara] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Knjizara] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Knjizara] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Knjizara] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Knjizara] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Knjizara] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Knjizara] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Knjizara] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Knjizara] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Knjizara] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Knjizara] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Knjizara] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Knjizara] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Knjizara] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Knjizara] SET RECOVERY FULL 
GO

ALTER DATABASE [Knjizara] SET  MULTI_USER 
GO

ALTER DATABASE [Knjizara] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Knjizara] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Knjizara] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Knjizara] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Knjizara] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Knjizara] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Knjizara] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Knjizara] SET  READ_WRITE 
GO

