//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaRacuna
    {
        public int IDStavkaRacuna { get; set; }
        public int IDRacuna { get; set; }
        public int IDKnjige { get; set; }
        public int kolicina { get; set; }
        public float jedCena { get; set; }
    
        public virtual Knjiga Knjiga { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
