//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaNarudzbenice
    {
        public int IDStavkaNarudzbenice { get; set; }
        public int IDNarudzbenice { get; set; }
        public int redBroj { get; set; }
        public int IDKnjige { get; set; }
        public int kolicina { get; set; }
    
        public virtual Magacin Magacin { get; set; }
        public virtual Narudzbenica Narudzbenica1 { get; set; }
    }
}
